name = "molonglo-constructions"
main = ".open-next/worker.js"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "molonglo-constructions"

[observability]
enabled = true

[vars]
ADMIN_EMAIL = "jatin@jatinvohra.com"
NEXT_PUBLIC_SITE_URL = "https://molonglo-constructions.jatin-a2c.workers.dev"
NEXT_PUBLIC_SUPABASE_URL = "https://vloamtiochlgrvouafgm.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsb2FtdGlvY2hsZ3J2b3VhZmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyMzY4NzQsImV4cCI6MjA5MjgxMjg3NH0.2e1DQNTTsk7rFo5nn85sNuYEzbH4UWrm6qtjjrKUZws"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_bgu-rj8HIrZp2pYSSOOAHw_mrHe3Xim"
